function [textHandle, bgHandle] = DrawCellLabel(curAx, drawString, x, y, colorStruct)
    global Figures
    
    bgHandle = [];
    
    if ( ~Figures.cells.showInterior )
        bgHandle = plot(curAx, x, y, colorStruct.shape,...
                'MarkerFaceColor',  colorStruct.back,...
                'MarkerEdgeColor',  colorStruct.edge,...
                'MarkerSize',       colorStruct.shapeSize);
    end

    textHandle = text(x, y, drawString,...
        'Parent',               curAx,...
        'Color',                colorStruct.text,...
        'BackgroundColor',      colorStruct.textBack,...
        'FontWeight',           colorStruct.fontWeight,...
        'FontSize',             colorStruct.fontSize,...
        'HorizontalAlignment',  'center');
end