function AddLockedField()
    global CellFamilies
    
    oldCellFamilies = CellFamilies;
    
    CellFamilies = struct(...
        'rootTrackID',  {oldCellFamilies.rootTrackID},...
        'tracks', {oldCellFamilies.tracks},...
        'startTime', {oldCellFamilies.startTime},...
        'endTime', {oldCellFamilies.endTime},...
        'bLocked', {false});
end