function AddUserEditedField()
    global CellHulls
    
    oldCellHulls = CellHulls;
    CellHulls = struct(...
        'time',         {oldCellHulls.time},...
        'points',       {oldCellHulls.points},...
        'centerOfMass',	{oldCellHulls.centerOfMass},...
        'indexPixels',	{oldCellHulls.indexPixels},...
        'imagePixels',	{oldCellHulls.imagePixels},...
        'deleted',      {oldCellHulls.deleted},...
        'userEdited',   {0});
end